### ISSUE TITLE
Failing to build THD package

### ISSUE THREAD

**Issue by VirrageS** [apaszke/pytorch-dist#55]
When I try to build THD package I get
```
ld: library not found for -lTH
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libTHD.dylib] Error 1
make[1]: *** [CMakeFiles/THD.dir/all] Error 2
make: *** [all] Error 2
```

It looks like on Linux it builds properly. So I guess it can be a problem with some configuration, but I cannot find what can be wrong.

Before the rebase it was working properly.

My `DYLD_LIBRARY_PATH` looks like this:
```
export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:/Users/virrages/pytorch-dist/torch/lib"
```

**Comment by apaszke** [comment]
What command do you use to build it?

**Comment by VirrageS** [comment]
`./build.sh` in `pytorch-dist/torch/lib/THD`

**Comment by apaszke** [comment]
I can try to debug it in the evening. You can see the full compiler commands if you run `VERBOSE=1 ./build.sh`. Still, it's not a script that I care about very much. All that matters is that it can be built with `setup.py`.

**Comment by VirrageS** [comment]
Sure, it is just helpful to see if C++ tests build and run properly.

**Comment by VirrageS** [comment]
So I have been trying random things and I found out that when I added
```
-DTH_LIBRARIES="${lib_dir}/libTH.1.dylib" \
```
to `cmake` command in `build.sh` it works.

Full `cmake` command:
```
cmake .. -DCMAKE_CXX_FLAGS=" -I${lib_dir}/tmp_install/include -pthread "  \
         -DCMAKE_SHARED_LINKER_FLAGS="-L${lib_dir}/tmp_install/lib " \
         -DTH_LIBRARIES="${lib_dir}/libTH.1.dylib" \
         -DCMAKE_EXE_LINKER_FLAGS="-L${lib_dir}/tmp_install/lib -pthread " \
   -DTorch_FOUND="1"
``` 

Is this legit fix?

**Comment by apaszke** [comment]
Right, that should do it.
