### ISSUE TITLE
Install instructions don't work

### ISSUE THREAD

**Issue by roryj78** [apaszke/pytorch-dist#92]
Hi All

I'm using your install instructions at: 
https://github.com/apaszke/pytorch-dist/wiki/PyTorch-(with-torch.distributed)-installation-on-Linux

I am on a fresh install Ubuntu 17.04 server, 4.10.0-19-generic, Python 3.5.3, GCC 6.3.0

1. There are differences in your install instructions between the first _tl;dr_ script and the detailed version (most obviously python vs python3 in the last few lines)

2. _Neither_ method works for me. Using either method the "WITH_DISTRIBUTED=1 python(or 3) setup.py build_deps" step gives multiple errors...
 [  4%] Building NVCC (Device) object CMakeFiles/THC.dir/THC_generated_THCSleep.cu.o
 **/usr/bin/ccache: invalid option -- 'E'**
...
CMakeFiles/THC.dir/build.make:70: recipe for target 'CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o' failed
make[2]: *** [CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
**/usr/bin/ccache: invalid option -- 'E'**

any help please? (thanks in advance)

( I installed cmake with the wget and boostrap as per instructions and 
"ccache is already the newest version (3.3.3-1)" )

**Comment by 0mp** [comment]
Hi! As far as I know everything, which was worthwhile in this repository has been already merged with the [upstream][1] as it is mentioned in the latest v0.2.0 release: https://github.com/pytorch/pytorch/releases/tag/v0.2.0

Secondly, the installation instruction on the wiki page you've linked might be a out-of-date (I haven't check though). 

Is there a reason why you want to compile this repository? You can use prebuilt binaries of the upstream PyTorch from http://pytorch.org/ (it works fine for most common use cases).

 [1]: https://github.com/pytorch/pytorch

**Comment by roryj78** [comment]
Thank you - I've had a lot more luck with the upstream pyTorch now (originally found your install guide after failing there) - now i've gone down the Anaconda route, all working much better!
